Repository mozilla-bteam/bmo, pull requests merged in 2018-09, with the labels that each got.

#762 Bug 1470536 - Add new GeckoView product to easy product selector on Browse and Enter Bug pages
  extensions/BMO/template/en/default/global/choose-product.html.tmpl
  extensions/BMO/web/styles/choose_product.css
Labels: stakeholder request

#752 Bug 1492346 - scripts/syncflags.pl should also add the target product to any tracking flags that the source product is a member of
  scripts/syncflags.pl
Labels: small

#761 Bug 1473417 - Show often/recently used products/components on New Bug page
  extensions/BMO/template/en/default/global/choose-product.html.tmpl
  extensions/BMO/web/js/new-bug-frequent-comp.js
  extensions/BMO/web/styles/choose_product.css
  template/en/default/global/header.html.tmpl
Labels: UX, stakeholder request

#756 Bug 1489718 - Insert form widgets for approval flag requests instead of free-form comment text
  extensions/BMO/template/en/default/hook/flag/type_comment-form.html.tmpl
  extensions/FlagTypeComment/template/en/default/flag/type_comment.html.tmpl
  extensions/FlagTypeComment/web/js/ftc.js
  extensions/FlagTypeComment/web/styles/ftc.css
  skins/standard/attachment.css
  skins/standard/global.css
  template/en/default/flag/list.html.tmpl
Labels: UX, stakeholder request
