Repository mozilla-bteam/bmo, pull requests merged in 2018-12, with the labels that each got.

#967 Bug 1512424 - Comment Reply button is not working properly on Chrome
  extensions/BugModal/web/bug_modal.css
Labels: bug, small

#968 no bug - Add "Vagrant: Connect to Database" VS Code task
  .vscode/tasks.json
Labels: small

#961 Bug 1511558 - Guided form's Core Component dropdown list cannot be loaded
  extensions/GuidedBugEntry/web/js/guided.js
Labels: bug, perf

#936 Bug 1456878 - Support markdown comments
  Bugzilla.pm
  Bugzilla/Bug.pm
  Bugzilla/Comment.pm
  Bugzilla/Config/Advanced.pm
  Bugzilla/Markdown.pm
  Bugzilla/Template.pm
  Bugzilla/WebService/Bug.pm
  attachment.cgi
  docs/en/rst/api/core/v1/comment.rst
  extensions/BMO/template/en/default/email/bugmail.html.tmpl
  extensions/BugModal/template/en/default/bug_modal/activity_stream.html.tmpl
  extensions/BugModal/template/en/default/bug_modal/new_comment.html.tmpl
  extensions/BugModal/web/bug_modal.css
  extensions/BugModal/web/bug_modal.js
  extensions/EditComments/lib/WebService.pm
  process_bug.cgi
  skins/standard/global.css
  t/008filter.t
  t/markdown.t
  template/en/default/admin/params/advanced.html.tmpl
  template/en/default/bug/comment.html.tmpl
Labels: UX

#981 Bug 1514765 - fix new bug comment preview
  template/en/default/bug/comment.html.tmpl
Labels: small

#983 Bug 1515144 - Prevent Google Analytics script from being loaded when DNT:1 so that Tracking Protection doesn't have to block it
  extensions/GoogleAnalytics/template/en/default/hook/global/header-additional_header.html.tmpl
  extensions/GoogleAnalytics/template/en/default/hook/global/header-start.html.tmpl
  extensions/GoogleAnalytics/web/js/analytics.js
  extensions/GoogleAnalytics/web/js/dnt-helper.js
Labels: small

#866 Bug 1493253 - Embed crash count table to bug pages
  Bugzilla/CGI.pm
  extensions/BMO/template/en/default/hook/bug/show-header-end.html.tmpl
  extensions/BMO/template/en/default/hook/bug_modal/header-end.html.tmpl
  extensions/BMO/web/js/firefox-crash-table.js
Labels: stakeholder request
