Repository mozilla-bteam/bmo, pull requests merged in 2018-10, with the labels that each got.

#768 Bug 1494645 - Allow customizing HTML <title> of search results
  buglist.cgi
  template/en/default/list/list.html.tmpl
Labels: small

#767 Bug 1421032 - Detect Markdown attachment files as text/plain so Firefox can display the content
  js/attachment.js
Labels: small

#795 Bug 1496233 - "Dunno" -> "Don't know" in approval request form
  extensions/BMO/template/en/default/hook/flag/type_comment-form.html.tmpl
Labels: small

#797 Bug 1489120 - Add a rest API to get triage owners for each product/component pair
  Bugzilla/WebService/Product.pm
  docs/en/rst/api/core/v1/product.rst
Labels: API, small, stakeholder request

#796 Bug 1495746 - /app/static/metricsgraphics/css/google-OpenSans.css missing in app container
  public/metricsgraphics/socorro-lens.html
Labels: small

#813 Bug 1497234 - Remove Personas Plus GitHub link from Custom Bug Entry Forms index
  extensions/BMO/template/en/default/bug/create/custom_forms.none.tmpl
Labels: small

#816 no bug - Update README on VS Code integration
  README.rst
Labels: small

#812 Bug 1497070 - In-page links are broken due to <base href> added during Mojo migration
  template/en/default/global/header.html.tmpl
Labels: small

#819 Bug 1497437 - The crash graph should display Exact Match results by default
  public/metricsgraphics/socorro-lens.html
Labels: small, stakeholder request

#826 Bug 1495741 - memory issues: Avoid copying stuff in the webservice layer so much
  Bugzilla/WebService/JSON.pm
  Bugzilla/WebService/JSON/Box.pm
  Bugzilla/WebService/Server/JSONRPC.pm
  Bugzilla/WebService/Server/REST.pm
  t/json-boxes.t
Labels: API, perf

#827 Bug 1495741 - memory issues: disable etag generation for /rest/product
  Bugzilla/WebService/Product.pm
  Bugzilla/WebService/Server.pm
Labels: API, small

#822 Bug 1495741 - memory issues: use local flag cache
  Bugzilla/WebService/Product.pm
Labels: API, perf, small

#835 Bug 1009716 - Add (Cmd|Ctrl)+Enter shortcut for submitting from text areas.
  js/field.js
Labels: UX, small

#843 no bug - saner defaults for pre-forking servers
  Bugzilla/Quantum.pm
  README.rst
Labels: small

#841 Bug 1497077 followup - Convert links to absolute path
  template/en/default/admin/params/query.html.tmpl
  template/en/default/bug/dependency-graph.html.tmpl
  template/en/default/bug/dependency-tree.html.tmpl
Labels: small

#844 Bug 1499417 - Change BMO docs links from bmo.readthedocs.org to .io
  conf/checksetup_answers.txt
  contribute.json
  extensions/ContributorEngagement/template/en/default/contributor/email.txt.tmpl
  template/en/default/account/prefs/apikey.html.tmpl
  vagrant_support/checksetup_answers.j2
Labels: small

#788 Bug 1496004 - Improve layout of attachment detail page, hide comment form when custom form is inserted
  extensions/FlagTypeComment/web/js/ftc.js
  extensions/FlagTypeComment/web/styles/ftc.css
  extensions/Review/template/en/default/hook/flag/list-requestee.html.tmpl
  extensions/Review/web/styles/review.css
  skins/standard/attachment.css
  template/en/default/attachment/edit.html.tmpl
Labels: stakeholder request

#733 Bug 1487171 - Allow setting bug flags when creating/updating attachment with API
  Bugzilla/WebService/Bug.pm
  docs/en/rst/api/core/v1/attachment.rst
Labels: API, perl review

#850 Bug 1497077 followup - Convert links to absolute path
  extensions/BMO/template/en/default/pages/get_permissions.html.tmpl
  extensions/Voting/template/en/default/pages/voting.html.tmpl
  template/en/default/account/prefs/mfa.html.tmpl
  template/en/default/admin/classifications/footer.html.tmpl
  template/en/default/admin/groups/create.html.tmpl
  template/en/default/bug/edit.html.tmpl
  template/en/default/bug/show-header.html.tmpl
  template/en/default/global/header.html.tmpl
  template/en/default/list/list.html.tmpl
  template/en/default/mfa/duo/verify.html.tmpl
Labels: small

#728 Bug 1469733 - Fix scrolling glitch on Safari
  skins/standard/global.css
Labels: small

#855 Bug 1370855 - Restrict Referer to same-origin
  Bugzilla/CGI.pm
Labels: small

#854 Bug 1501893 - Tell robots to leave the graphs alone, and leave a trap
  template/en/default/robots.txt.tmpl
Labels: small

#852 reportingMTA is optional
  Bugzilla/Quantum/SES.pm
Labels: small

#856 Bug 1501133 - Attachment flags layout on new bug page is broken
  skins/standard/attachment.css
Labels: small

#867 Bug 1479535 - BUGZILLA.bug_url is wrong on bug page after POSTed, Copy Summary doesn’t work as expected
  extensions/BugModal/template/en/default/bug_modal/header.html.tmpl
  extensions/OpenGraph/template/en/default/hook/global/header-start.html.tmpl
Labels: small

#871 Bug 1503162 - Approval request form is incomplete in some cases
  extensions/FlagTypeComment/template/en/default/flag/type_comment.html.tmpl
Labels: small

#872 Bug 1503182 - Fix data type of native bug count API return value
  Bugzilla/WebService/Bug.pm
Labels: API, small
