Repository mozilla-bteam/bmo, pull requests merged in 2018-11, with the labels that each got.

#880 Bug 1503705 - Stop serving HTML-prettyprinted JSON as REST API results
  Bugzilla/WebService/Constants.pm
  Bugzilla/WebService/Server/REST.pm
  docs/en/rst/api/core/v1/general.rst
  template/en/default/rest.html.tmpl
Labels: API

#881 Bug 1503748 - Trackpad swipe navigation and mobile horizontal scrolling broken, vertical scrolling partially broken when zoomed
  skins/standard/global.css
Labels: small

#725 Bug 1485303 - lists in component descriptions break describecomponents.cgi layout
  extensions/BugModal/web/bug_modal.css
  skins/standard/describecomponents.css
  template/en/default/reports/components.html.tmpl
Labels: small

#726 Bug 1482338 - "Search Bugs" field has "cursor: pointer" style while it's text field
  skins/standard/global.css
Labels: small

#890 Bug 1436619 - followup: ignore "http://" in URL field
  Bugzilla/Bug.pm
Labels: small

#889 Bug 1505762 - count_only=1 results in error with REST API
  Bugzilla/WebService/Bug.pm
Labels: API, small

#891 Bug 1505793 - Add triage owner in /rest/bug
  Bugzilla/WebService/Bug.pm
  docs/en/rst/api/core/v1/bug.rst
Labels: API, stakeholder request

#894 Revert "Bug 1505793 - Add triage owner in /rest/bug"
  Bugzilla/WebService/Bug.pm
  docs/en/rst/api/core/v1/bug.rst
Labels: API

#896 Bug 1505793 - Add triage owner in /rest/bug
  Bugzilla/WebService/Bug.pm
  docs/en/rst/api/core/v1/bug.rst
Labels: API, stakeholder request

#897 Bug 1351116 - github issue links are not expanded in parentheses
  extensions/BMO/Extension.pm
Labels: bug, small

#893 Bug 1505831 - Add nick field to all user objects including *_detail returned by /rest/bug
  Bugzilla/WebService/Bug.pm
  Bugzilla/WebService/Group.pm
  Bugzilla/WebService/User.pm
  docs/en/rst/api/core/v1/bug.rst
  docs/en/rst/api/core/v1/flag-activity.rst
  docs/en/rst/api/core/v1/group.rst
  docs/en/rst/api/core/v1/user.rst
  extensions/Review/lib/WebService.pm
  qa/t/webservice_user_get.t
Labels: API, stakeholder request

#691 Bug 1480042 - Request queue dropdown badge shows empty names for some display names
  extensions/Review/web/js/badge.js
  request.cgi
  template/en/default/request/queue.csv.tmpl
  template/en/default/request/queue.html.tmpl
  template/en/default/request/queue.json.tmpl
Labels: bug

#908 Bug 1484892 schema change only - Add is_hidden column to longdescs_activity
  extensions/EditComments/Extension.pm
Labels: small

#736 Bug 1484892 - Modify EditComments extension to let anyone use it conditionally and support inline editing
  Bugzilla/Template.pm
  extensions/BugModal/template/en/default/bug_modal/activity_stream.html.tmpl
  extensions/BugModal/web/bug_modal.css
  extensions/BugModal/web/comments.js
  extensions/EditComments/Extension.pm
  extensions/EditComments/lib/WebService.pm
  extensions/EditComments/template/en/default/hook/admin/params/editparams-current_panel.html.tmpl
  extensions/EditComments/template/en/default/hook/bug_modal/activity_stream-comment_action.html.tmpl
  extensions/EditComments/template/en/default/hook/bug_modal/activity_stream-comment_meta.html.tmpl
  extensions/EditComments/template/en/default/hook/bug_modal/header-end.html.tmpl
  extensions/EditComments/template/en/default/hook/global/header-start.html.tmpl
  extensions/EditComments/template/en/default/pages/comment-revisions.html.tmpl
  extensions/EditComments/template/en/default/pages/editcomments.html.tmpl
  extensions/EditComments/web/js/editcomments.js
  extensions/EditComments/web/js/inline-editor.js
  extensions/EditComments/web/js/revisions.js
  extensions/EditComments/web/styles/editcomments.css
  extensions/EditComments/web/styles/inline-editor.css
  extensions/EditComments/web/styles/revisions.css
  qa/t/test_bug_edit.t
  scripts/generate_bmo_data.pl
  skins/standard/global.css
  template/en/default/global/code-error.html.tmpl
Labels: UX, perl review

#919 Bug 1507867 - splinter review links in emails are missing host/scheme, rendering them unusable
  extensions/Splinter/Extension.pm
  extensions/Splinter/lib/Util.pm
  extensions/Splinter/template/en/default/hook/request/email-after_summary.txt.tmpl
Labels: bug, perl review, small

#912 Bug 1507518 - Allow title parameter value in url to be the title of the page
  skins/standard/buglist.css
  template/en/default/list/list.html.tmpl
Labels: small, stakeholder request

#921 Bug 324535 - Allow the use of relative dates in charts
  Bugzilla/Chart.pm
  Bugzilla/Util/DateTime.pm
  extensions/BMO/lib/Reports/ReleaseTracking.pm
  extensions/BMO/lib/Reports/UserActivity.pm
Labels: small

#236 Update quicksearch.html.tmpl
  template/en/default/pages/quicksearch.html.tmpl
Labels: small

#933 Bug 1351116 followup - Don't match regular links
  extensions/BMO/Extension.pm
Labels: bug, small

#934 Bug 1508903 - internal error on requests.cgi: Bad argument param sent to Bugzilla::User::new function.
  request.cgi
  template/en/default/request/queue.csv.tmpl
  template/en/default/request/queue.html.tmpl
  template/en/default/request/queue.json.tmpl
Labels: bug, small

#940 Bug 1499697 - Update triage owner list to include all Firefox-related major products and stop saying __Any__
  extensions/BMO/lib/Reports/Triage.pm
  extensions/BMO/template/en/default/pages/triage_owners.html.tmpl
Labels: small, stakeholder request

#953 Bug 1510832 - Adding a trailing space to a comment causes an error
  extensions/EditComments/web/js/inline-editor.js
Labels: bug, small

#952 Bug 1510109 - Implement per-product new bug comment templates (schema change only)
  Bugzilla/DB/Schema.pm
  Bugzilla/Install/DB.pm
Labels: small

#957 Bug 1511158 - Enhance comment action button style
  extensions/BugModal/template/en/default/bug_modal/activity_stream.html.tmpl
  extensions/BugModal/web/bug_modal.css
Labels: small
