Repository mozilla-bteam/bmo, pull requests merged in 2018-03, with the labels that each got.

#422 Bug 1273381 - Improve bugzilla object performance by using Class::XSAccessor for object accessors
  Bugzilla/Attachment.pm
  Bugzilla/Bug.pm
  Bugzilla/BugUrl.pm
  Bugzilla/BugUserLastVisit.pm
  Bugzilla/Classification.pm
  Bugzilla/Comment.pm
  Bugzilla/Comment/TagWeights.pm
  Bugzilla/Component.pm
  Bugzilla/Field.pm
  Bugzilla/Field/Choice.pm
  Bugzilla/Flag.pm
  Bugzilla/FlagType.pm
  Bugzilla/Group.pm
  Bugzilla/Keyword.pm
  Bugzilla/Milestone.pm
  Bugzilla/Object.pm
  Bugzilla/Product.pm
  Bugzilla/Search/Recent.pm
  Bugzilla/Search/Saved.pm
  Bugzilla/User.pm
  Bugzilla/User/APIKey.pm
  Bugzilla/User/Session.pm
  Bugzilla/Version.pm
  Bugzilla/Whine.pm
  Bugzilla/Whine/Query.pm
  Bugzilla/Whine/Schedule.pm
  extensions/BugmailFilter/lib/Filter.pm
  extensions/MyDashboard/lib/BugInterest.pm
  extensions/Push/lib/BacklogMessage.pm
  extensions/Push/lib/Backoff.pm
  extensions/Push/lib/LogEntry.pm
  extensions/Push/lib/Message.pm
  extensions/Push/lib/Option.pm
  extensions/Review/lib/FlagStateActivity.pm
  extensions/TrackingFlags/lib/Flag.pm
  extensions/TrackingFlags/lib/Flag/Bug.pm
  extensions/TrackingFlags/lib/Flag/Value.pm
  extensions/TrackingFlags/lib/Flag/Visibility.pm
  t/bugzilla-objects-def.t
Labels: needs review

#375 Bug 1419973 - Modify product selector layout on Browse and Enter Bug pages
  extensions/BMO/template/en/default/global/choose-product.html.tmpl
  extensions/BMO/web/styles/choose_product.css
Labels: needs review

#372 Bug 1429344 - Review requests in requests dropdown should link to MozReview or GitHub instead of Bugzilla details page
  extensions/Review/web/js/badge.js
  request.cgi
  template/en/default/global/header.html.tmpl
  template/en/default/request/queue.json.tmpl
Labels: needs review

#349 no bug - add a contributing.md
  CONTRIBUTING.md
Labels: in progress, needs review, no bug

#445 Bug 1443057 - Backport 1136125 to bmo - Reduce memory usage of Bugzilla::CGI->send_cookie()
  Bugzilla/CGI.pm
Labels: needs review, perl review

#443 Bug 1443049 - is_interactive() must be declared before log4perl config is loaded
  Bugzilla/Logging.pm
Labels: needs review, perl review

#447 Bug 1343248 - make secbugstats do less work
  contrib/secbugstats/bin/curlbug.py
  contrib/secbugstats/bin/gather.sh
Labels: needs review

#440 Bug 1441181 - Step 7 - Fix bug in catch_signal()
  Bugzilla/DaemonControl.pm
  t/daemon-control-catch-signal.t
Labels: needs review, perl review

#459 Bug 1444088 - review link for patches on the requests page no longer shows up
  extensions/Splinter/template/en/default/hook/request/queue-after_column.html.tmpl
Labels: needs review

#325 Bug 1427503 - Allow all users to use Duo as the MFA provider.
  template/en/default/account/prefs/mfa.html.tmpl
Labels: blocked

#437 Bug 1441181 - Step 4 - Re-implement subprocess code with IO::Async
  Bugzilla/Install/Filesystem.pm
  Bugzilla/JobQueue.pm
  Bugzilla/JobQueue/Runner.pm
  Bugzilla/JobQueue/Worker.pm
  jobqueue-worker.pl
  jobqueue.pl
Labels: needs review

#444 Bug 1443058 - Backport 1087400 to bmo - CGI 4.05 throws tons of "CGI::param called in list context" warnings
  Bugzilla/CGI.pm
Labels: needs review, perl review

#413 Bug 1441244 - prevent compounding error messages in tests
  Bugzilla/Error.pm
Labels: needs review, perl review
