Repository mozilla-bteam/bmo, pull requests merged in 2019-04, with the labels that each got.

#1147 Bug 1477931 follow-up - Make sure Gravatar and requests are loaded via API
  Bugzilla/WebService/User.pm
  js/field.js
  skins/standard/global.css
Labels: bug, small

#1185 Bug 1522348 part 2 - Add support for bugbug-generated bug list
  extensions/BMO/Extension.pm
  extensions/BMO/bin/migrate-bug-type.pl
Labels: perl review, small, stakeholder request

#1168 Bug 1538383 - Allow to hide inline preview when attaching a file, e.g. SVG crashtests.
  Bugzilla/Attachment.pm
  js/attachment.js
  template/en/default/attachment/createformcontents.html.tmpl
Labels: bug, small

#1183 Bug 1539302 - Add "attachment is patch" field to bug
  extensions/BMO/Extension.pm
Labels: stakeholder request

#1143 Bug 1531757 - Allow to search only in bug description (comment 0) with both Quick and Advenced Search as well as API
  Bugzilla/Search.pm
  Bugzilla/Search/Quicksearch.pm
  Bugzilla/WebService/Bug.pm
  docs/en/rst/api/core/v1/bug.rst
  template/en/default/pages/quicksearch.html.tmpl
  template/en/default/search/form.html.tmpl
Labels: API, stakeholder request

#1181 Bug 1539941 - Link keywords and flags in bug detail to searches (and later graphing)
  extensions/BugModal/template/en/default/bug_modal/activity_stream.html.tmpl
  extensions/BugModal/template/en/default/bug_modal/edit.html.tmpl
  extensions/BugModal/template/en/default/bug_modal/tracking_flags.html.tmpl
Labels: stakeholder request

#1188 Bug 1541111 - Separate bugs on Triage Owners page by type
  extensions/BMO/lib/Reports/Triage.pm
  extensions/BMO/template/en/default/pages/triage_owners.html.tmpl
  extensions/BMO/web/styles/triage_reports.css
Labels: stakeholder request

#1193 Bug 1281200 - New show_bug.cgi view should have an option to have fields editable by default.
  extensions/BugModal/template/en/default/bug_modal/edit.html.tmpl
  extensions/BugModal/web/bug_modal.js
  skins/standard/global.css
Labels: stakeholder request

#1174 Bug 1071066 - For bugs with aliases, inline history displays the bug number rather than the bug alias
  Bugzilla/Template.pm
  extensions/BugModal/template/en/default/bug_modal/activity_stream.html.tmpl
  template/en/default/bug/activity/table.html.tmpl
Labels: small

#1145 Bug 1283392 - Query for history or comment containing private bug id should return no data for this bug
  Bugzilla/WebService/Bug.pm
Labels: API, bug, small, stakeholder request

#1194 Bug 1344427 - Display "nn people including you" if current user is cc'ed on a bug.
  extensions/BugModal/template/en/default/bug_modal/edit.html.tmpl
  extensions/BugModal/web/bug_modal.js
Labels: bug, small

#1197 Bug 1541582 - Set qe-verify to + when manual QA requested upon uplift
  extensions/FlagTypeComment/web/js/ftc.js
Labels: small

#1199 Bug 1541123 - "1 new change since last visit" shown for the change I just submitted
  extensions/BugModal/web/bug_modal.js
Labels: bug, small

#1203 Bug 1541231 - Certain Phablicator requests are displayed as inline attachment
  extensions/BugModal/template/en/default/bug_modal/activity_stream.html.tmpl
  extensions/BugModal/web/comments.js
Labels: bug, small

#1088 Bug 1152434 - Remove regressing bug ID field from uplift approval request once regressed-by field is added
  extensions/BMO/template/en/default/hook/flag/type_comment-form.html.tmpl
Labels: small, stakeholder request

#1210 Bug 1541484 - Move the bug type from header to module and de-emphasize it so it’s not confused with bug status
  extensions/BugModal/template/en/default/bug_modal/edit.html.tmpl
  skins/standard/global.css
Labels: bug, small

#1213 Bug 1539908 - Replace no_break filter with CSS nowrap
  Bugzilla/Template.pm
  extensions/BMO/template/en/default/global/choose-product.html.tmpl
  extensions/BMO/template/en/default/pages/triage_reports.html.tmpl
  extensions/BMO/template/en/default/pages/user_activity.html.tmpl
  extensions/BMO/web/styles/reports.css
  extensions/BMO/web/styles/triage_reports.css
  extensions/BugModal/template/en/default/bug_modal/flags.html.tmpl
  extensions/BugModal/web/bug_modal.css
  extensions/BugmailFilter/template/en/default/account/prefs/bugmail_filter.html.tmpl
  extensions/BugmailFilter/web/style/bugmail-filter.css
  extensions/GuidedBugEntry/template/en/default/guided/guided.html.tmpl
  extensions/MyDashboard/template/en/default/pages/mydashboard.html.tmpl
  extensions/MyDashboard/web/styles/mydashboard.css
  skins/standard/global.css
  template/en/default/admin/flag-type/list.html.tmpl
  template/en/default/attachment/list.html.tmpl
  template/en/default/bug/show-multiple.html.tmpl
  template/en/default/flag/list.html.tmpl
  template/en/default/global/choose-product.html.tmpl
  template/en/default/global/header-search-dropdown.html.tmpl
Labels: bug

#1214 Bug 1542882 - Don't do image preview on security bugs
  extensions/BugModal/web/comments.js
Labels: small

#1192 Bug 1541133 - Bug type field should be a radio button
  extensions/BugModal/template/en/default/bug_modal/edit.html.tmpl
  extensions/BugModal/template/en/default/bug_modal/field.html.tmpl
  extensions/BugModal/web/bug_modal.css
  extensions/BugModal/web/bug_modal.js
  qa/t/test_bug_edit.t
  qa/t/test_custom_fields.t
  skins/standard/enter_bug.css
  skins/standard/global.css
  template/en/default/bug/create/create.html.tmpl
  template/en/default/bug/field-label.html.tmpl
  template/en/default/bug/field.html.tmpl
Labels: UX

#1209 Bug 1527459 - Display dependency bugs by type, using the same colour/icon for each
  extensions/BugModal/template/en/default/bug_modal/edit.html.tmpl
  extensions/BugModal/template/en/default/bug_modal/field.html.tmpl
  extensions/BugModal/web/bug_modal.css
Labels: small, stakeholder request

#1207 no bug - Add instructions for HTTPS in localdev to README
  README.rst
Labels: small

#1189 Bug 1531481 - Add bug type labels to My Dashboard
  extensions/MyDashboard/lib/Queries.pm
  extensions/MyDashboard/web/js/query.js
  extensions/MyDashboard/web/styles/mydashboard.css
Labels: small

#1217 no bug - Fix Triage Owner list throwing if predefined product is not found
  extensions/BMO/lib/Reports/Triage.pm
Labels: bug, small

#1222 no bug - Fix missing object error when submitting new bug
  Bugzilla.pm
  post_bug.cgi
Labels: bug, small

#1195 Bug 1541303 - Default component bug type is not set as expected; enhancement severity is still used for existing bugs
  extensions/BMO/bin/migrate-bug-type.pl
Labels: bug, small

#1227 Bug 1543760 - When cloning a bug, the bug is added to 'Regressed by' of the new bug
  enter_bug.cgi
Labels: bug, small

#1228 Bug 1543718 - Obsolete attachments should have a strikethrough
  extensions/BugModal/web/bug_modal.css
Labels: bug, small

#1229 Bug 1543798 - Do not treat email addresses with invalid.bugs as unassigned when displaying bugs
  extensions/BMO/Extension.pm
  extensions/BugModal/template/en/default/bug_modal/edit.html.tmpl
  extensions/ComponentWatching/Extension.pm
  template/en/default/attachment/create.html.tmpl
Labels: bug, small

#1233 Bug 1544304 - Wrong escaping of quotes in attachment titles.
  extensions/BugModal/web/comments.js
  extensions/FlagTypeComment/web/js/ftc.js
Labels: bug, small

#1244 Bug 1345750 - "Depends on" and "Blocks" bug lists should still show list of bug links in edit mode
  extensions/BugModal/template/en/default/bug_modal/field.html.tmpl
  extensions/BugModal/web/bug_modal.css
Labels: bug, small, stakeholder request

#1240 no bug - Show Crash Signature field on Taskcluster bugs
  extensions/BMO/lib/Data.pm
Labels: small, stakeholder request

#1230 Bug 1544059 - Cloning a bug as a blocker doesn't copy the 'component' field
  extensions/BugModal/template/en/default/bug_modal/edit.html.tmpl
Labels: bug, small

#1226 Bug 1543741 - Blocklist requests getting filed as 'defect' instead of 'task' because of custom form
  Bugzilla/Bug.pm
Labels: bug, small

#1225 Bug 1543456 - Keep bug type passed to enter_bug.cgi via query, including cloned bug, even after component is selected
  template/en/default/bug/create/create.html.tmpl
Labels: bug, small, stakeholder request

#1249 Bug 1546539 - [SEO] Many legacy and printable bug pages are cached by Google
  extensions/BugModal/Extension.pm
  extensions/BugModal/template/en/default/bug_modal/edit.html.tmpl
  qa/t/test_bug_edit.t
  qa/t/test_custom_fields.t
  qa/t/test_long_list_redirection.t
  template/en/default/bug/navigate.html.tmpl
  template/en/default/global/site-navigation.html.tmpl
Labels: WIP, bug, small

#1250 Bug 1546774 - Show Dependency Tree link even if there’s only one bug
  extensions/BugModal/template/en/default/bug_modal/edit.html.tmpl
Labels: bug, small

#1253 Bug 1546624 - Add a 'everchanged' operator
  Bugzilla/Search.pm
  template/en/default/global/field-descs.none.tmpl
  template/en/default/list/list.html.tmpl
  template/en/default/search/boolean-charts.html.tmpl
Labels: stakeholder request

#1224 Bug 1543438 - Enter Bug page: Hide Severity and Mentors as advanced fields
  extensions/Review/template/en/default/hook/bug/create/create-after_custom_fields.html.tmpl
  skins/standard/enter_bug.css
  template/en/default/bug/create/create.html.tmpl
Labels: small

#1216 Bug 1543189 - Add search pronouns: %triageowner% and %self%
  Bugzilla/Search.pm
  docs/en/rst/using/finding.rst
Labels: small, stakeholder request

#1211 Bug 1541617 - Allow Products to set a default bug type.
  Bugzilla/Component.pm
  Bugzilla/DB/Schema.pm
  Bugzilla/Install/DB.pm
  Bugzilla/Product.pm
  Bugzilla/WebService/Product.pm
  docs/en/rst/api/core/v1/product.rst
  editproducts.cgi
  template/en/default/admin/components/edit-common.html.tmpl
  template/en/default/admin/default_select.html.tmpl
  template/en/default/admin/products/edit-common.html.tmpl
  template/en/default/admin/products/list.html.tmpl
  template/en/default/admin/products/updated.html.tmpl
Labels: perl review, stakeholder request

#1254 Bug 1547098 - Limit the height of code in Markdown so the horizontal scrollbar can be found and used easily
  skins/standard/global.css
Labels: small

#1256 Bug 1535574 - Reply to Markdown comment adds extra line above quoted text but not below
  extensions/BugModal/web/bug_modal.js
Labels: bug, small
