Repository mozilla-bteam/bmo, pull requests merged in 2019-01, with the labels that each got.

#1017 Bug 1493253 follow up - Set CSP for crash table iframe
  Bugzilla/CGI.pm
Labels: bug, small

#1021 Bug 1493253 follow up - bump the version
  extensions/BMO/web/js/firefox-crash-table.js
Labels: small, stakeholder request

#1023 Bug 1518328 - The edit comment feature should have a preview mode as well
  extensions/EditComments/template/en/default/hook/global/header-start.html.tmpl
  extensions/EditComments/web/js/inline-editor.js
  extensions/EditComments/web/styles/inline-editor.css
Labels: UX

#1041 Bug 1520495 - Crash count table does not detect uplift links in Markdown comments
  extensions/BMO/web/js/firefox-crash-table.js
Labels: bug, small, stakeholder request

#1043 Bug 1520495 followup - Crash count table does not detect uplift links in Markdown comments
  extensions/BMO/web/js/firefox-crash-table.js
Labels: bug, small, stakeholder request

#1049 Bug 1511261 - request queue page shows 'Bugzilla::User=HASH(...)' instead of username
  template/en/default/request/queue.html.tmpl
Labels: bug, small

#1050 Bug 1520856 - "Opt out of these emails" at bottom of overdue request nagging emails doesn't open desired page
  extensions/RequestNagger/template/en/default/email/request_nagging-user.html.tmpl
  extensions/RequestNagger/template/en/default/email/request_nagging-user.txt.tmpl
Labels: bug, small

#1055 Bug 1520533 - Utilize Markdown in uplift form comments
  extensions/FlagTypeComment/web/js/ftc.js
Labels: small, stakeholder request

#1056 Bug 1521653 - Cannot edit comments after creating or updating an attachment
  extensions/EditComments/template/en/default/hook/global/header-start.html.tmpl
Labels: bug, small

#1063 Bug 1522601 - Uplift request question and answer don't show up as comments
  extensions/FlagTypeComment/web/js/ftc.js
Labels: bug, small

#1071 Bug 1519782 - The OrangeFactor extension should link back to Intermittent Failure View using '&tree=all'
  extensions/OrangeFactor/web/js/orange_factor.js
Labels: small, stakeholder request

#1073 Bug 1523172 - Advanced Search link on home page doesn’t always take me to Advanced Search
  template/en/default/index.html.tmpl
Labels: bug, small

#1070 Bug 1433080 - No longer show the template for tracking & release notes requests
  extensions/BugModal/template/en/default/bug_modal/header.html.tmpl
  extensions/TrackingFlags/template/en/default/hook/bug/show-header-end.html.tmpl
  extensions/TrackingFlags/template/en/default/hook/global/header-start.html.tmpl
  extensions/TrackingFlags/web/js/flags.js
Labels: bug, small, stakeholder request

#1074 Bug 1522731 - When you click "Update comment", the button changes size and the "Cancel" button jumps underneath your cursor, causing momentary panic that you canceled your edit
  extensions/EditComments/web/js/inline-editor.js
Labels: bug, small

#1061 Bug 1512815 - Make Bugzilla->active_custom_wants() 10x faster when using specific include_fields
  Bugzilla.pm
  Bugzilla/WebService.pm
  Bugzilla/WebService/Bug.pm
  extensions/TrackingFlags/Extension.pm
Labels: API, perf, perl review

#1075 Bug 1523317 - Exclude Graveyard products from QuickSearch results
  Bugzilla/Hook.pm
  Bugzilla/Search/Quicksearch.pm
  extensions/BMO/Extension.pm
  extensions/TrackingFlags/Extension.pm
  t/quicksearch.t
Labels: perl review, stakeholder request

#1079 Bug 1524158 - markdown generated by approval comment form could be improved
  extensions/FlagTypeComment/web/js/ftc.js
Labels: small

#1080 Bug 1512815 followup - incorrectly checking for exclude _custom
  Bugzilla.pm
Labels: small
