Repository mozilla-bteam/bmo, pull requests merged in 2019-07, with the labels that each got.

#1356 Bug 1563269 - Stray "from" when redirecting needinfo
  extensions/Needinfo/template/en/default/bug/needinfo.html.tmpl
Labels: bug, small

#1357 Bug 1563312 - Needinfo links at top of bug goes to #c0 rather than relevant comment
  Bugzilla/DB/Mysql.pm
  Bugzilla/DB/Oracle.pm
  Bugzilla/DB/Pg.pm
  Bugzilla/DB/Sqlite.pm
  Bugzilla/Flag.pm
  extensions/BMO/lib/Reports/UserActivity.pm
  extensions/InlineHistory/Extension.pm
  request.cgi
Labels: bug, small

#1325 Bug 1557799 - Search By Change History: date range is ignored when field is not specified
  extensions/BMO/web/js/advanced-search.js
  js/advanced-search.js
  js/field.js
  qa/t/test_bug_edit.t
  skins/standard/search_form.css
  template/en/default/search/form.html.tmpl
Labels: UX, bug, stakeholder request

#1364 Bug 1380437 follow-up - Send API token only if available
  js/util.js
Labels: bug, small

#1370 Bug 1566079 - User autocomplete doesn’t work for requestee for certain flags
  js/field.js
Labels: bug, small

#1367 Bug 1563868 update documentation for searching on bugs by group restriction
  docs/en/rst/using/finding.rst
Labels: doc, small

#1369 Bug 1565741 - Let users choose defect or enhancement on guided bug entry form
  extensions/GuidedBugEntry/template/en/default/guided/guided.html.tmpl
Labels: small

#1232 Bug 1541898 - Allow to search on product/component pair
  Bugzilla/Search.pm
Labels: perl review, small, stakeholder request

#1312 Bug 1252298 - schema only
  Bugzilla/DB/Schema.pm
  Bugzilla/Install/DB.pm
Labels: blocked, small

#1172 Bug 1533717 - Add a search keyword "Whatever"
  Bugzilla/Field.pm
  Bugzilla/Search.pm
  js/advanced-search.js
  template/en/default/global/field-descs.none.tmpl
Labels: perl review, stakeholder request

#1277 Bug 1546717 - Add the ability to search on count gt/lt/eq
  Bugzilla/Bug.pm
  Bugzilla/Field.pm
  Bugzilla/Search.pm
  Bugzilla/Search/ClauseGroup.pm
  Bugzilla/WebService/Bug.pm
  bugzilla.dtd
  docs/en/rst/api/core/v1/bug.rst
  extensions/BMO/Extension.pm
  extensions/BMO/template/en/default/hook/global/field-descs-end.none.tmpl
  extensions/BugmailFilter/lib/Constants.pm
  template/en/default/global/field-descs.none.tmpl
  template/en/default/list/table.html.tmpl
  template/en/default/pages/bugzilla.dtd.tmpl
Labels: stakeholder request

#1371 Bug 1562651 - My Dashboard broken, reporting "Failed to load last changes from Bugzilla"
  Bugzilla/Bug.pm
Labels: bug

#1365 Bug 1565319 - FF Version selection does not update from client version, shows previous reported version
  enter_bug.cgi
  extensions/GuidedBugEntry/web/js/guided.js
  post_bug.cgi
Labels: defect, small

#1363 Bug 1563360 - End key does not scroll all the way to the bottom of BMO page
  extensions/BugModal/web/bug_modal.css
  extensions/BugModal/web/comments.js
  skins/standard/global.css
Labels: defect

#1382 Bug 1568259 - Short URL generation isn't working
  extensions/Bitly/web/js/bitly.js
Labels: defect, small

#1386 Bug 1568863 - Prefilled comment will be wiped after changing component
  template/en/default/bug/create/create.html.tmpl
Labels: defect, small

#1385 no bug - Fix an error in regex
  Bugzilla/Search.pm
Labels: defect, small

#1383 Bug 1533269 - Tooltip displayed at wrong position when page is zoomed or scrolled, and reappears after switching back tab
  extensions/BugModal/web/bug_modal.js
Labels: defect, small

#1391 Bug 1555508 - Cursor does not change to hand (cursor: pointer) when mouse is over "Edit Bug" or "Save Changes" buttons
  extensions/BugModal/web/bug_modal.css
  skins/standard/buglist.css
  skins/standard/global.css
Labels: UX, defect, small

#1390 Bug 1569194 - My Dashboard shows Unexpected Error dialog when request is aborted while loading
  extensions/MyDashboard/web/js/flags.js
  extensions/MyDashboard/web/js/query.js
Labels: defect, small

#1389 Bug 1568592 - Custom fields are lost when using Edit Search
  query.cgi
Labels: defect, stakeholder request

#1384 Bug 1568704 - Allow to use --- as empty Resolution field value in Custom Search
  Bugzilla/Search.pm
Labels: small, stakeholder request

#1395 no bug - Remove WOFF 1.0 files
  skins/standard/fonts/FiraGO-Book.woff
  skins/standard/fonts/FiraGO-BookItalic.woff
  skins/standard/fonts/FiraGO-Medium.woff
  skins/standard/fonts/FiraGO-MediumItalic.woff
  skins/standard/fonts/FiraGO-SemiBold.woff
  skins/standard/fonts/FiraGO-SemiBoldItalic.woff
  skins/standard/fonts/MaterialIcons-Regular.woff
  skins/standard/fonts/NotoMono-Regular.woff
  skins/standard/global.css
Labels: small
