Repository mozilla-bteam/bmo, pull requests merged in 2020-04, with the labels that each got.

#1545 Bug 1626543 - Some fields on enter bug page do not have associated labels
  extensions/BMO/template/en/default/hook/bug/create/create-after_custom_fields.html.tmpl
  extensions/BMO/template/en/default/hook/bug/create/create-end.html.tmpl
  extensions/Needinfo/template/en/default/hook/bug/create/create-after_custom_fields.html.tmpl
  extensions/Review/template/en/default/hook/bug/create/create-after_custom_fields.html.tmpl
  extensions/UserStory/template/en/default/hook/bug/create/create-after_custom_fields.html.tmpl
  js/attachment.js
  skins/standard/attachment.css
  template/en/default/attachment/createformcontents.html.tmpl
  template/en/default/bug/comment.html.tmpl
  template/en/default/bug/create/create.html.tmpl
  template/en/default/bug/field-label.html.tmpl
  template/en/default/bug/field.html.tmpl
  template/en/default/flag/list.html.tmpl
  template/en/default/global/header.html.tmpl
  template/en/default/global/textarea.html.tmpl
  template/en/default/global/userselect.html.tmpl
Labels: defect

#1548 Bug 1627601 - Copy Summary function doesn’t work properly if the bug summary contains HTML tags
  extensions/BugModal/web/bug_modal.js
Labels: defect, small

#1555 Bug 1632038 - Remove number of people from bug update toast notification
  extensions/BugModal/template/en/default/bug/show-modal.html.tmpl
Labels: small

#1556 Bug 1632624 - When adding vars to the fields data that is logged to stack driver, convert to a JSON string
  Bugzilla/Error.pm
Labels: small

#1557 Bug 1632994 - [Bugzilla.App] Can't use an undefined value as a subroutine reference at /app/Bugzilla/Error.pm line 94.
  Bugzilla/Error.pm
Labels: small

#1558 Bug 1633848 - Fix possible areas where memory leak can occur in the PhabBugz daemon code
  extensions/PhabBugz/lib/Revision.pm
  extensions/PhabBugz/lib/User.pm
Labels: small
